
// This file was auto-generated by ML.NET Model Builder. 

using PredictPromotionModel_ConsoleApp2;

// Create single instance of sample data from first line of dataset for model input
PredictPromotionModel.ModelInput sampleData = new PredictPromotionModel.ModelInput()
{
    Person_id_ = 2F,
    Department_ = @"First,",
    First_name_ = @"Francis,",
    Last_name_ = @"Haywood,",
    Age_ = 39F,
    City_ = @"Judson,",
    State_ = @"SC,",
    Country_ = @"United States,",
    Rating_ = 7F,
    Experience_ = 15F,
    Salary = 4100F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Promotion_ with predicted Promotion_ from sample data...\n\n");


Console.WriteLine($"Person_id_: {2F}");
Console.WriteLine($"Department_: {@"First,"}");
Console.WriteLine($"First_name_: {@"Francis,"}");
Console.WriteLine($"Last_name_: {@"Haywood,"}");
Console.WriteLine($"Age_: {39F}");
Console.WriteLine($"City_: {@"Judson,"}");
Console.WriteLine($"State_: {@"SC,"}");
Console.WriteLine($"Country_: {@"United States,"}");
Console.WriteLine($"Rating_: {7F}");
Console.WriteLine($"Experience_: {15F}");
Console.WriteLine($"Promotion_: {@"Yes,"}");
Console.WriteLine($"Salary: {4100F}");


var sortedScoresWithLabel = PredictPromotionModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

