
// This file was auto-generated by ML.NET Model Builder. 

using PredictCityModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
PredictCityModel.ModelInput sampleData = new PredictCityModel.ModelInput()
{
    Person_id = 2F,
    Department = @"First",
    First_name = @"Francis",
    Last_name = @"Haywood",
    Age = 39F,
    State = @"SC",
    Country = @"United States",
    Rating = 7F,
    Experience = 15F,
    Promotion = @"Yes",
    Salary = 4100F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual City with predicted City from sample data...\n\n");


Console.WriteLine($"Person_id: {2F}");
Console.WriteLine($"Department: {@"First"}");
Console.WriteLine($"First_name: {@"Francis"}");
Console.WriteLine($"Last_name: {@"Haywood"}");
Console.WriteLine($"Age: {39F}");
Console.WriteLine($"City: {@"Judson"}");
Console.WriteLine($"State: {@"SC"}");
Console.WriteLine($"Country: {@"United States"}");
Console.WriteLine($"Rating: {7F}");
Console.WriteLine($"Experience: {15F}");
Console.WriteLine($"Promotion: {@"Yes"}");
Console.WriteLine($"Salary: {4100F}");


var sortedScoresWithLabel = PredictCityModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

