
// This file was auto-generated by ML.NET Model Builder. 

using PredictNumberModel;

// Create single instance of sample data from first line of dataset for model input
PredictNumberModel.PredictNumberModel.ModelInput sampleData = new PredictNumberModel.PredictNumberModel.ModelInput()
{
    Person_id_ = @"2,",
    Department_ = @"First,",
    First_name_ = @"Francis,",
    Last_name_ = @"Haywood,",
    Age_ = 39F,
    City_ = @"Judson,",
    State_ = @"SC,",
    Country_ = @"United States,",
    Rating_ = 7F,
    Experience_ = 15F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Salary with predicted Salary from sample data...\n\n");


Console.WriteLine($"Person_id_: {@"2,"}");
Console.WriteLine($"Department_: {@"First,"}");
Console.WriteLine($"First_name_: {@"Francis,"}");
Console.WriteLine($"Last_name_: {@"Haywood,"}");
Console.WriteLine($"Age_: {39F}");
Console.WriteLine($"City_: {@"Judson,"}");
Console.WriteLine($"State_: {@"SC,"}");
Console.WriteLine($"Country_: {@"United States,"}");
Console.WriteLine($"Rating_: {7F}");
Console.WriteLine($"Experience_: {15F}");
Console.WriteLine($"Salary: {4100F}");


var predictionResult = PredictNumberModel.PredictNumberModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Salary: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

